### PR TITLE
chore: add code style formatting and license headers

### LINKED ISSUE #25: Code style definition and checks
Defining common code style rules prevents commits to being bloated with not significant changes, such as spaces, import order, etc.
Agree on code style and add automation for checking rules.

### PR DESCRIPTION
**Pull request by Dudeplayz**
Adds the spotless maven plugin and applies the [palantir java format](https://github.com/palantir/palantir-java-format) together with a license header to all files.

Closes #25

### CODE REVIEW

**Comment by Dudeplayz** [comment]
Run `mvn spotless:check` to see all style violations and run `mvn spotless:apply` to fix it.
Currently is the palantir format configured, because I think it has some good additions to the google format.
Also a configuration for the typescript files can be configured.

**Comment by Dudeplayz** [comment]
By default the `spotless:check` goal is run on verify. If it is run on an earlier stage like compile the github actions would fail, which is preferable.

**Comment by mcollovati** [comment]
Good job!

There are some formatting that I do not like that much (for example the constructors with an argument per line) but it is just a matter of personal taste.
However, the most important thing for me is to have a shared style that can be able to apply both from the IDE and the command line.
I tested quickly the palantir plugin for IDEA, and it seems to work fine.

For the automation, I would not bind the plugin to a maven phase, but instead have an additional job in the validation workflow that runs the check and adds some comment to the PR.

A couple of cons:
* if the check fails, it stops the build even if `--fail-at-end` is given.
* the summary in the console logs is truncated, so it is not possible to have the full list of offending files

What I would to do in the new job is:

* run `spotless:check` only for the files modified in the PR (`-DspotlessFiles`)
* if the check fails, run `spotless:apply` and save the `git diff` as a job attachment
* add/update a comment in the PR to confirm formatting is ok or inform about offending files, link to the diff, and command to apply the formatting

I did not yet checked if there's already some github action that does that work. Will do asap

**Comment by mcollovati** [comment]
The github action formatting job can be handled in a separate PR/ticket.
I would focus this PR on configuring the plugin

**Comment by Dudeplayz** [comment]
> There are some formatting that I do not like that much (for example the constructors with an argument per line) but it is just a matter of personal taste.

You can also test prettier or the google formatting. If you prefer them more?

> However, the most important thing for me is to have a shared style that can be able to apply both from the IDE and the command line.

I agree to the IDE support.

> For the automation, I would not bind the plugin to a maven phase, but instead have an additional job in the validation workflow that runs the check and adds some comment to the PR.

Thats a good idea.

Some thoughts to the diff and comment on the PR:
- Whats about letting an action or bot apply the formatting always before merge?
- Otherwise the diff could also be shown as suggestion comment, so it could be applied fast (if not to much).
- Or combine both and trigger an auto apply over the comments.

**Comment by mcollovati** [comment]
I don't like to have formatting applyed automatically without possibility to check it.
But I like the idea of trigger it with a comment on the PR 👍

For the diff I would prefer a file, instead of inline it as a comment, because it may be a huge amount of text

**Comment by Dudeplayz** [comment]
> I don't like to have formatting applyed automatically without possibility to check it.

Understandable, then lets make it triggerable somehow.



> For the diff I would prefer a file, instead of inline it as a comment, because it may be a huge amount of text

True. Depending on the effort, we could inline comment it to an specific extend and for everything more go with the diff. Maybe there is even a better option provided by github.

**Comment by Dudeplayz** [comment]
We can also add a license header now.

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
