### PR TITLE
feat: add support for client endpoints live reload

### LINKED ISSUE #261: Investigate on Hilla Endpoint Hot-Reload support
Investigate if the new [Hilla Endpoint Hot-Reload](https://github.com/vaadin/hilla/pull/1146/files) feature can be implemented in the Quarkus extension.

### LINKED ISSUE #489: Investigate usages of ApplicationContextProvider
Investigate on usages of ApplicationContextProvider class and verify if the extension should provide such bean.

### PR DESCRIPTION
**Pull request by mcollovati**
Adds the possibility to watch for changes in Hilla Java endpoints and trigger Quarkus live reload without the need to refresh the brower page. Quarkus will recompile the changed class and restart the server if needed.
If 'quarkus.live-reload.instrumentation' is enabled, Quarkus may redefine the class without a server restart. In this case, the extension directly triggers Hilla hotswapper to regenerate client side code.

Fixes #261
Fixes #489

### CODE REVIEW

**Comment by mcollovati** [comment]
This live reload implementation works only with Java source files.
@Dudeplayz would you be interested in expanding it for Kotlin?

**Comment by Dudeplayz** [comment]
> This live reload implementation works only with Java source files.
> 
> @Dudeplayz would you be interested in expanding it for Kotlin?

Definitely interested in, but have to check it. Have you testet it with Kotlin, maybe it works OOB?

**Comment by mcollovati** [comment]
Manually tested, but needs some automated test

**Comment by mcollovati** [comment]
> Definitely interested in, but have to check it. Have you testet it with Kotlin, maybe it works OOB?

Nope, not tested with Kotlin at all. But I'm quite sure it will not work, since there is a check for file names ending in `.java` :smile:

**Comment by Dudeplayz** [comment]
> Nope, not tested with Kotlin at all. But I'm quite sure it will not work, since there is a check for file names ending in `.java` :smile: 

Ah ok. Can you reference where the 'java' check is?

**Comment by mcollovati** [comment]
It is in  EndpointSourcesWatcher class.
But the real issue is that to detect if the changed source should trigger endpoint generation it:

* computes a class name based on the changed file name
* uses JavaParser lib to detect all types declaration (inner classes, interfaces, records,...) in the source code

The above steps most likely won't work for kotlin code

**Comment by mcollovati** [comment]
Now endpoints live reload has two strategies to watch for changes:

* SOURCE: watches for changes in source folders (e.g. `src/main/java`); computes the file name from the class fine and as a second option parses the source to check for internal type declarations and classes with Hilla annotations.
* CLASS: watches for changes in `.class` files in the build folder (e.g. `target/classes`). It computes class name from the file name and, as a second option, it loads the class definitions to check for presence of Hilla annotation.


CLASS strategy seems to work fine with Kotlin. SOURCE strategy needs an implementation, for example to detect multiple types defined in the same source file.

**Pull request merged**
